; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-poe]
platform = espressif32
board = esp32-poe
framework = arduino
monitor_speed = 115200
lib_deps =
  # RECOMMENDED
  # Accept new functionality in a backwards compatible manner and patches
  EEPROM @ ^2.0.0
  # this code doesn't look the same as what I had brought directly into src:
  # old eeprom.cpp had this at the top of the file
  
  # EEPROM.h -ported by Paolo Becchi to Esp32 from esp8266 EEPROM
  #         -Modified by Elochukwu Ifediora <ifedioraelochukwuc@gmail.com>
  #         -Converted to nvs lbernstone@gmail.com

  #Uses a nvs byte array to emulate EEPROM

  #Copyright (c) 2014 Ivan Grokhotkov. All rights reserved.
  #This file is part of the esp8266 core for Arduino environment.